# Generated by Django 4.2.2 on 2024-11-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_rename_voucher_liberacao_id_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
