# Generated by Django 4.2.2 on 2024-11-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0003_alter_voucher_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liberacao',
            name='telefone',
            field=models.CharField(max_length=14),
        ),
    ]
