# Generated by Django 2.0 on 2022-09-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='hora_fechamento_vendas',
            field=models.TimeField(default='23:59:59', verbose_name='Horário do Fechamento das Vendas'),
        ),
    ]
