# Generated by Django 4.2.2 on 2026-04-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0002_auto_20220902_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='mp_access_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mercado Pago Access Token'),
        ),
        migrations.AddField(
            model_name='config',
            name='webhook_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Webhook URL'),
        ),
    ]
