# Generated by Django 4.2.2 on 2026-04-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0003_config_mp_access_token_config_webhook_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('admin', 'Administrador'), ('lanchonete', 'Lanchonete'), ('aluno', 'Aluno'), ('glanchonete', 'Gerência Lanchonete')], max_length=20, verbose_name='Tipo de Acesso')),
                ('ad_group', models.CharField(help_text='Nome do grupo no Active Directory', max_length=255, verbose_name='Grupo do AD')),
                ('allowed_menus', models.TextField(help_text='IDs dos menus permitidos separados por vírgula', verbose_name='Menus Permitidos')),
            ],
            options={
                'verbose_name': 'Permissão de Menu',
                'verbose_name_plural': 'Permissões de Menu',
                'unique_together': {('access_type', 'ad_group')},
            },
        ),
    ]
