# Generated by Django 4.2.2 on 2026-04-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0004_menupermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='menupermission',
            name='can_sell',
            field=models.BooleanField(default=False, verbose_name='Pode realizar venda?'),
        ),
        migrations.AddField(
            model_name='menupermission',
            name='can_switch_dashboard',
            field=models.BooleanField(default=False, verbose_name='Pode trocar de Dashboard?'),
        ),
        migrations.AddField(
            model_name='menupermission',
            name='default_dashboard',
            field=models.CharField(choices=[('usuario', 'Dashboard Usuário (Estudante)'), ('funcionario', 'Dashboard Funcionário (Gestão/Vendas)')], default='usuario', max_length=20, verbose_name='Dashboard Padrão'),
        ),
        migrations.AddField(
            model_name='menupermission',
            name='quick_access',
            field=models.TextField(blank=True, help_text='IDs dos atalhos separados por vírgula (ex: vendas_manual, validacao_qr, cardapio_dia, relatorios)', verbose_name='Atalhos de Acesso Rápido'),
        ),
    ]
