# Generated by Django 4.2.2 on 2026-04-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0005_menupermission_can_sell_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menupermission',
            name='group_label',
            field=models.CharField(blank=True, help_text='Ex: Administrador, Vendedor, Coordenador', max_length=50, verbose_name='Rótulo do Grupo'),
        ),
    ]
