# Generated by Django 4.2.2 on 2026-04-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0006_menupermission_group_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='pix_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Taxa PIX (R$)'),
        ),
    ]
