# Generated by Django 4.2.2 on 2026-04-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0007_config_pix_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='pix_test_mode',
            field=models.BooleanField(default=False, verbose_name='Modo Teste PIX'),
        ),
        migrations.AlterField(
            model_name='config',
            name='pix_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Taxa PIX (%)'),
        ),
    ]
