# Generated by Django 4.2.2 on 2026-04-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0008_config_pix_test_mode_alter_config_pix_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menupermission',
            name='access_type',
            field=models.CharField(choices=[('admin', 'Administrador'), ('lanchonete', 'Lanchonete'), ('aluno', 'Aluno'), ('servidor', 'Servidor'), ('glanchonete', 'Gerência Lanchonete')], max_length=20, verbose_name='Tipo de Acesso'),
        ),
    ]
