# Generated by Django 4.2.2 on 2026-04-06 15:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_prato_preco_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('valor', models.FloatField(verbose_name='Valor Pago')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('usado', models.BooleanField(default=False)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.aluno')),
            ],
        ),
    ]
