# Generated by Django 4.2.2 on 2026-04-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_estudante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketaluno',
            name='data_utilizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Utilização'),
        ),
    ]
