# Generated by Django 4.2.2 on 2026-04-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_estudante', '0002_ticketaluno_data_utilizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketaluno',
            name='tipo_refeicao',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de Refeição'),
        ),
    ]
