# Generated by Django 4.2.2 on 2026-04-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_estudante', '0003_ticketaluno_tipo_refeicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketaluno',
            name='data_utilizacao',
        ),
        migrations.RemoveField(
            model_name='ticketaluno',
            name='tipo_refeicao',
        ),
        migrations.RemoveField(
            model_name='ticketaluno',
            name='usado',
        ),
        migrations.AddField(
            model_name='ticketaluno',
            name='id_pagamento_externo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Pagamento Externo'),
        ),
        migrations.AddField(
            model_name='ticketaluno',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='Pago?'),
        ),
        migrations.AddField(
            model_name='ticketaluno',
            name='pix_copia_e_cola',
            field=models.TextField(blank=True, null=True, verbose_name='PIX Copia e Cola'),
        ),
        migrations.AddField(
            model_name='ticketaluno',
            name='pix_qr_code_base64',
            field=models.TextField(blank=True, null=True, verbose_name='PIX QR Code Base64'),
        ),
    ]
