# Generated by Django 4.2.2 on 2026-04-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_estudante', '0004_remove_ticketaluno_data_utilizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketaluno',
            name='tipo_refeicao',
            field=models.CharField(default='Almoço', max_length=15, verbose_name='Tipo de Refeição'),
        ),
        migrations.AddField(
            model_name='ticketaluno',
            name='usado',
            field=models.BooleanField(default=False, verbose_name='Usado?'),
        ),
    ]
