# Generated by Django 4.2.2 on 2026-04-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_estudante', '0005_ticketaluno_tipo_refeicao_ticketaluno_usado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketaluno',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento'),
        ),
        migrations.AddField(
            model_name='ticketaluno',
            name='data_utilizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Uso'),
        ),
    ]
