# Generated by Django 4.2.2 on 2026-04-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_estudante', '0006_ticketaluno_data_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketaluno',
            name='detalhe_adicionais',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhe Adicionais'),
        ),
        migrations.AddField(
            model_name='ticketaluno',
            name='valor_adicionais',
            field=models.FloatField(default=0.0, verbose_name='Valor Adicionais'),
        ),
        migrations.AlterField(
            model_name='ticketaluno',
            name='valor',
            field=models.FloatField(verbose_name='Valor do Prato'),
        ),
    ]
