# Generated by Django 4.2.2 on 2026-04-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_estudante', '0007_ticketaluno_detalhe_adicionais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketaluno',
            name='valor_taxa',
            field=models.FloatField(default=0.0, verbose_name='Valor da Taxa'),
        ),
    ]
