# Generated by Django 4.2.2 on 2026-04-23 12:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_prato_preco_servidor_servidor'),
        ('ticket_estudante', '0008_ticketaluno_valor_taxa'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketServidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('valor', models.FloatField(verbose_name='Valor do Prato')),
                ('valor_adicionais', models.FloatField(default=0.0, verbose_name='Valor Adicionais')),
                ('valor_taxa', models.FloatField(default=0.0, verbose_name='Valor da Taxa')),
                ('detalhe_adicionais', models.TextField(blank=True, null=True, verbose_name='Detalhe Adicionais')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pago', models.BooleanField(default=False, verbose_name='Pago?')),
                ('usado', models.BooleanField(default=False, verbose_name='Usado?')),
                ('tipo_refeicao', models.CharField(default='Almoço', max_length=15, verbose_name='Tipo de Refeição')),
                ('data_utilizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Uso')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('id_pagamento_externo', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Pagamento Externo')),
                ('pix_copia_e_cola', models.TextField(blank=True, null=True, verbose_name='PIX Copia e Cola')),
                ('pix_qr_code_base64', models.TextField(blank=True, null=True, verbose_name='PIX QR Code Base64')),
                ('id_servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.servidor')),
            ],
        ),
    ]
