# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=11, unique=True)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='prato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=200)),
                ('preco', models.FloatField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField()),
                ('rotulo', models.CharField(max_length=11)),
                ('status', models.BooleanField()),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='usuariorestaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('valor', models.FloatField()),
                ('id_prato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prato')),
                ('id_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ticket')),
                ('id_usuario_restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuariorestaurante')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='id_pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pessoa'),
        ),
        migrations.AddField(
            model_name='admin',
            name='id_pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pessoa'),
        ),
    ]
