# Generated by Django 2.0 on 2022-09-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alunoscem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='usuario',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
