# Generated by Django 2.0 on 2022-09-15 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220913_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunoscem',
            name='id_pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pessoa', unique=True),
        ),
    ]
