# Generated by Django 2.0 on 2023-05-08 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220915_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='alunoscolaboradores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pessoa', unique=True)),
            ],
        ),
    ]
