# Generated by Django 4.2.2 on 2024-04-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alunoscolaboradores'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='cem',
            field=models.BooleanField(default=False),
        ),
    ]
