# Generated by Django 4.2.2 on 2026-04-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_venda_cem'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='preco_aluno',
            field=models.FloatField(default=0.0, verbose_name='Preço Aluno'),
        ),
    ]
