# Generated by Django 4.2.2 on 2026-04-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_prato_preco_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardapioDia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('ALMOCO', 'Almoço'), ('JANTA', 'Janta')], max_length=10)),
                ('itens', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cardápio do Dia',
                'verbose_name_plural': 'Cardápios do Dia',
                'unique_together': {('data', 'tipo')},
            },
        ),
    ]
