# Generated by Django 4.2.2 on 2026-04-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cardapiodia'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcaoAlimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(choices=[('Proteínas', 'Proteínas'), ('Acompanhamentos', 'Acompanhamentos'), ('Saladas', 'Saladas'), ('Sobremesas', 'Sobremesas'), ('Bebidas/Sucos', 'Bebidas/Sucos')], max_length=30)),
            ],
            options={
                'verbose_name': 'Opção de Alimento',
                'verbose_name_plural': 'Opções de Alimentos',
                'ordering': ['categoria', 'nome'],
            },
        ),
    ]
