# Generated by Django 4.2.2 on 2026-04-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_opcaoalimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='origem',
            field=models.CharField(default='MANUAL', max_length=10),
        ),
    ]
