# Generated by Django 4.2.2 on 2026-04-23 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_adicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='preco_servidor',
            field=models.FloatField(default=0.0, verbose_name='Preço Servidor'),
        ),
        migrations.CreateModel(
            name='servidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pessoa')),
            ],
        ),
    ]
