# Generated by Django 4.2.2 on 2026-04-23 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_estudante', '0009_ticketservidor'),
        ('core', '0014_prato_preco_servidor_servidor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaServidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('valor_pago', models.FloatField()),
                ('id_prato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.prato')),
                ('id_servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.servidor')),
                ('id_ticket_servidor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket_estudante.ticketservidor')),
                ('id_usuario_restaurante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.usuariorestaurante')),
            ],
        ),
    ]
