# Generated by Django 4.2.2 on 2026-04-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_vendaservidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='siap',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SIAPE'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
    ]
